#!/bin/bash
cd ..
git clone https://github.com/iosdevzone/IDZBuild
export PATH=`pwd`/IDZBuild:$PATH
git clone https://github.com/iosdevzone/IDZPrecompiledOgg
mkdir -p IDZBuildRoot
export IDZ_BUILD_ROOT=`pwd`/IDZBuildRoot
. IDZPrecompiledOgg/libogg_build.bash
. IDZPrecompiledVorbis/libvorbis_build.bash
